export const colors = [
    { name: "Red", hex: "#FF0000" },
    { name: "Lime", hex: "#00FF00" },
    { name: "Blue", hex: "#0000FF" },
    { name: "Yellow", hex: "#FFFF00" },
    { name: "Fuchsia", hex: "#FF00FF" },
    { name: "Cyan", hex: "#00FFFF" },
    { name: "Black", hex: "#000000" },
    { name: "White", hex: "#FFFFFF" },
    { name: "Gray", hex: "#808080" },
    { name: "Maroon", hex: "#800000" },
    { name: "Olive", hex: "#808000" },
    { name: "Green", hex: "#008000" },
    { name: "Purple", hex: "#800080" },
    { name: "Teal", hex: "#008080" },
    { name: "Navy", hex: "#000080" },
    { name: "Orange", hex: "#FFA500" },
    { name: "Brown", hex: "#A52A2A" },
    { name: "Pink", hex: "#FFC0CB" },
    { name: "Gold", hex: "#FFD700" },
    { name: "Green Yellow", hex: "#ADFF2F" },
    { name: "Indigo", hex: "#4B0082" },
    { name: "Violet", hex: "#EE82EE" },
    { name: "Khaki", hex: "#F0E68C" },
    { name: "Chocolate", hex: "#D2691E" },
    { name: "Saddle Brown", hex: "#8B4513" },
    { name: "Sea Green", hex: "#2E8B57" },
    { name: "Cadet Blue", hex: "#5F9EA0" },
    { name: "Tan", hex: "#D2B48C" },
    { name: "Tomato", hex: "#FF6347" },
    { name: "Turquoise", hex: "#40E0D0" },
    { name: "Pale Green", hex: "#98FB98" },
    { name: "Medium Purple", hex: "#9370DB" },
    { name: "Medium Sea Green", hex: "#3CB371" },
    { name: "Medium Slate Blue", hex: "#7B68EE" },
    { name: "Medium Spring Green", hex: "#00FA9A" },
    { name: "Medium Turquoise", hex: "#48D1CC" },
    { name: "Medium Violet Red", hex: "#C71585" },
    { name: "Midnight Blue", hex: "#191970" },
    { name: "Mint Cream", hex: "#F5FFFA" },
    { name: "Misty Rose", hex: "#FFE4E1" },
    { name: "Lavender", hex: "#E6E6FA" },
    { name: "Salmon", hex: "#FA8072" },
    { name: "Coral", hex: "#FF7F50" },
    { name: "Hot Pink", hex: "#FF69B4" }
];


export const sizes = ["XXS", "XS", "S", "M", "L", "XL", "XXL"];

export const ParentCategories = [
    "Bəzək əşyaları",
    "Bluzlar / Koftalar",
    "Don",
    "Uzun/qısaqol köynək / Polo",
    "Пальто",
    "Ətəklər",
    "Idman",
    "Üst geyimi",
    "Cins",
    "Sviter / Kardiqan",
    "Şalvarlar",
    "Alt paltarı / Gecə geyimi",
    "Çimərlik geyimləri",
    "Bel çantası",
    "Klaçlar",
    "Çiyindən asmalı çantalar",
    "Çiyindən aşırmalı çantalar",
    "Qulplu çantalar",
    "Kəmər çantalar",
    "Böyük həcmli çantalar",
    "Kəmərlər",
    "Pulqabılar / Cüzdanlar",
    "Gün eynəkləri",
    "Papaqlar",
    "Saç aksesuarları",
    "Corablar",
    "Kolqotqalar",
    "Digər",
    "Loferlər",
    "Qısaboğaz çəkmələr",
    "Espadrilyalar",
    "Baletkalar",
    "Myulilər",
    "Səndəllər",
    "Krossovka / Kedlər",
    "Tərliklər",
    "Ətriyyat",
    "Dəriyə qulluq",
    "Köynəklər",
    "Çantalar",
    "Kombinezonlar / Dəstlər",
    "Tuflilər",
    "Şortlar",
    "Куртки / Блейзеры",
    "Kombinezonlar",
    "Hədiyyə üçün",
    "Şamlar",
    "Qulluq",
    "Odekolon",
    "Diffuzer",
    "Əl kremi",
    "Ətir",
    "Sabun"
];

export const childs = [
    "Koftalar",
    "Qısaqol köynəklər",
    "Gödəkçələr",
    "Jiletlər",
    "Şalvarlar",
    "Svitşot",
    "Kardiqanlar",
    "Sviterlər",
    "Hudilər",
    "Polo",
    "Leqqinslər",
    "Maykalar",
    "Alt paltarları",
    "Pijamalar",
    "Klassik köynəklər",
    "Gündəlik şalvarlar",
    "Klassik şalvarlar",
    "Tərliklər",
    "Pencəklər"
];

